export { dateToMacTime, macTimeToDate } from "../../database/timestamps.ts";

const CONTACT_COLUMNS = `
    r.Z_PK as id,
    r.ZFIRSTNAME as firstName,
    r.ZLASTNAME as lastName,
    r.ZORGANIZATION as organization,
    r.ZJOBTITLE as jobTitle,
    r.ZDEPARTMENT as department,
    r.ZBIRTHDAY as birthday,
    r.ZCREATIONDATE as createdAt,
    r.ZMODIFICATIONDATE as modifiedAt,
    CASE WHEN r.ZIMAGEDATA IS NOT NULL THEN 1 ELSE 0 END as hasImage`;

export const LIST_CONTACTS = `
  SELECT ${CONTACT_COLUMNS}
  FROM ZABCDRECORD r
  WHERE r.Z_ENT = 22
  ORDER BY r.ZSORTINGLASTNAME ASC, r.ZSORTINGFIRSTNAME ASC
`;

export const GET_CONTACT = `
  SELECT ${CONTACT_COLUMNS}
  FROM ZABCDRECORD r
  WHERE r.Z_PK = ? AND r.Z_ENT = 22
`;

export const SEARCH_CONTACTS = `
  SELECT DISTINCT ${CONTACT_COLUMNS}
  FROM ZABCDRECORD r
  LEFT JOIN ZABCDPHONENUMBER p ON p.ZOWNER = r.Z_PK
  LEFT JOIN ZABCDEMAILADDRESS e ON e.ZOWNER = r.Z_PK
  WHERE r.Z_ENT = 22
    AND (
      r.ZFIRSTNAME LIKE ?
      OR r.ZLASTNAME LIKE ?
      OR r.ZORGANIZATION LIKE ?
      OR p.ZFULLNUMBER LIKE ?
      OR e.ZADDRESS LIKE ?
    )
  ORDER BY r.ZSORTINGLASTNAME ASC, r.ZSORTINGFIRSTNAME ASC
`;

export const LIST_CONTACTS_IN_GROUP = `
  SELECT ${CONTACT_COLUMNS}
  FROM ZABCDRECORD r
  JOIN Z_22PARENTGROUPS j ON j.Z_22CONTACTS = r.Z_PK
  WHERE j.Z_19PARENTGROUPS1 = ? AND r.Z_ENT = 22
  ORDER BY r.ZSORTINGLASTNAME ASC, r.ZSORTINGFIRSTNAME ASC
`;

export const LIST_EMAILS = `
  SELECT ZADDRESS as address, ZLABEL as label, ZISPRIMARY as isPrimary
  FROM ZABCDEMAILADDRESS WHERE ZOWNER = ?
  ORDER BY ZISPRIMARY DESC, ZORDERINGINDEX ASC
`;

export const LIST_PHONES = `
  SELECT ZFULLNUMBER as number, ZLABEL as label, ZISPRIMARY as isPrimary
  FROM ZABCDPHONENUMBER WHERE ZOWNER = ?
  ORDER BY ZISPRIMARY DESC, ZORDERINGINDEX ASC
`;

export const LIST_ADDRESSES = `
  SELECT ZSTREET as street, ZCITY as city, ZSTATE as state,
         ZZIPCODE as zipCode, ZCOUNTRYNAME as country, ZLABEL as label
  FROM ZABCDPOSTALADDRESS WHERE ZOWNER = ?
  ORDER BY ZORDERINGINDEX ASC
`;

export const LIST_URLS = `
  SELECT ZURL as url, ZLABEL as label
  FROM ZABCDURLADDRESS WHERE ZOWNER = ?
  ORDER BY ZORDERINGINDEX ASC
`;

export const LIST_SOCIAL_PROFILES = `
  SELECT ZURLSTRING as url, ZUSERIDENTIFIER as username,
         ZSERVICENAME as service, ZLABEL as label
  FROM ZABCDSOCIALPROFILE WHERE ZOWNER = ?
  ORDER BY ZORDERINGINDEX ASC
`;

export const LIST_RELATED_NAMES = `
  SELECT ZNAME as name, ZLABEL as label
  FROM ZABCDRELATEDNAME WHERE ZOWNER = ?
  ORDER BY ZORDERINGINDEX ASC
`;

export const LIST_CONTACT_DATES = `
  SELECT ZDATE as date, ZLABEL as label
  FROM ZABCDCONTACTDATE WHERE ZOWNER = ?
  ORDER BY ZORDERINGINDEX ASC
`;

export const LIST_CONTACT_NOTE = `
  SELECT ZTEXT as text
  FROM ZABCDNOTE WHERE ZCONTACT = ?
`;

export const LIST_GROUPS = `
  SELECT r.Z_PK as id, r.ZNAME as name
  FROM ZABCDRECORD r
  WHERE r.Z_ENT = 19
  ORDER BY r.ZNAME ASC
`;

export const GET_GROUP = `
  SELECT r.Z_PK as id, r.ZNAME as name
  FROM ZABCDRECORD r
  WHERE r.Z_PK = ? AND r.Z_ENT = 19
`;

export const COUNT_GROUP_MEMBERS = `
  SELECT Z_19PARENTGROUPS1 as groupId, COUNT(*) as count
  FROM Z_22PARENTGROUPS
  GROUP BY Z_19PARENTGROUPS1
`;
